import type { TensorType, TensorTimeReversal } from './tensorCalculator';

export interface GoldenFixture {
  group: string; // key into GENERATORS, e.g. "-3'm'"
  tensor: TensorType;
  tr: TensorTimeReversal;
  expected: string[];
  source: string;
  note?: string;
}

/**
 * Shared citation for fixtures derived directly from each group's GENERATORS entry
 * (tensorCalculator.ts) rather than transcribed from a printed table.
 *
 * Method: apply the rank-3/4 transformation law for polar (ED, EQ) and axial (MD)
 * tensors under time reversal -- Birss, "Symmetry and Magnetism" (1966), eq. 3.22
 * (polar) / 3.27 (axial) -- to the group generated by the listed generators, then
 * symmetrize the last two tensor indices. The transformation law and group-closure
 * algorithm were independently re-implemented (exact/sympy arithmetic) and verified
 * to reproduce all six pre-existing Tier-3 fixtures ('1','-1','222','mm2','4mm','32',
 * ED i-type) bit-for-bit before being applied to the groups below.
 */
const GENERATOR_DERIVATION =
  "Independently re-derived from this group's GENERATORS entry (tensorCalculator.ts) via " +
  'the rank-3/4 transformation law for polar/axial tensors under time reversal (Birss, ' +
  '"Symmetry and Magnetism" (1966), eq. 3.22 / 3.27) and last-two-index symmetrization; ' +
  're-implementation calibrated against the six pre-existing Tier-3 fixtures.';

const TABLE_4E_VERIFICATION =
  'Verified against Birss, "Symmetry and Magnetism" (1966), Table 4e (rank-3 polar ' +
  'tensor components), via the birss-tables repo (github.com/manganite/birss-tables). ' +
  'Table 4a maps each group to a symbol class (A_n–U_n); Table 4e gives the independent ' +
  'components for each class at rank n=3.';

export const GOLDEN_FIXTURES: GoldenFixture[] = [
  // --- Trigonal: -3'm' (Cr2O3) -----------------------------------------------------
  {
    group: "-3'm'",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}',
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note:
      "The canonical magnetic-SHG group: Cr2O3 below T_N is -3'm' and this c-type ED " +
      'tensor is the textbook magnetoelectric SHG source term (Fiebig et al., JOSA B 22, ' +
      "96 (2005)). Cross-check: -3'm' = H u theta*i*H with unitary subgroup H = 3m, and " +
      "for c-type ED this decomposition predicts -3'm'(ED,c) = 3m(ED,i) -- the relation " +
      'above is exactly the 3m i-type ED form.',
  },
  {
    group: "-3'm'",
    tensor: 'MD',
    tr: 'i',
    expected: [
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
    ],
    source: GENERATOR_DERIVATION,
    note:
      "Axial-tensor branch for the Cr2O3 group. i-type results depend only on the " +
      "group's rotation parts (trFactor = 1 regardless of isAntiUnitary for i-type), so " +
      "-3'm'(MD,i) = -3m(MD,i); this matches the existing '32' ED i-type golden fixture " +
      'form, reflecting that axial i-tensors of -3m equal polar i-tensors of its proper ' +
      'rotation subgroup 32.',
  },

  // --- Hexagonal: 6'mm' / 6m'm' (magnetic phases of 6mm, e.g. hexagonal manganites) -
  {
    group: "6'mm'",
    tensor: 'ED',
    tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note:
      "i-type results depend only on the rotation parts, so 6'mm'(ED,i) = 6mm(ED,i) " +
      '(same form as the existing 4mm i-type golden fixture).',
  },
  {
    group: "6'mm'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}'],
    source: GENERATOR_DERIVATION,
    note: "c-type SHG tensor for the 6'mm' magnetic phase of hexagonal manganites (e.g. some RMnO3 magnetic structures).",
  },
  {
    group: "6m'm'",
    tensor: 'ED',
    tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note: "i-type results depend only on the rotation parts, so 6m'm'(ED,i) = 6mm(ED,i), same as 6'mm'(ED,i).",
  },
  {
    group: "6m'm'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note:
      "c-type SHG tensor for the 6m'm' magnetic phase -- distinct from 6'mm'(ED,c) " +
      'above, pinning down which mirror carries the prime.',
  },

  // --- Triclinic family: -1' -------------------------------------------------------
  {
    group: "-1'",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xxx}',
      '\\chi_{xxy} = \\chi_{xyx}',
      '\\chi_{xxz} = \\chi_{xzx}',
      '\\chi_{xyy}',
      '\\chi_{xyz} = \\chi_{xzy}',
      '\\chi_{xzz}',
      '\\chi_{yxx}',
      '\\chi_{yxy} = \\chi_{yyx}',
      '\\chi_{yxz} = \\chi_{yzx}',
      '\\chi_{yyy}',
      '\\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{yzz}',
      '\\chi_{zxx}',
      '\\chi_{zxy} = \\chi_{zyx}',
      '\\chi_{zxz} = \\chi_{zzx}',
      '\\chi_{zyy}',
      '\\chi_{zyz} = \\chi_{zzy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note:
      "Triclinic Type-III family check. -1' = {1, i*theta} (inversion combined with " +
      'time reversal, no plain inversion). For c-type ED, every group element acts as ' +
      '+1 on the rank-3 tensor (the parity flip from inversion cancels the c-type sign ' +
      'flip), so all 18 last-two-index-symmetrized components survive independently -- ' +
      "the same count/shape as the existing point-group '1' fixture.",
  },

  // --- Monoclinic family: 2'/m' -----------------------------------------------------
  {
    group: "2'/m'",
    tensor: 'MD',
    tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx}',
      '\\chi_{xyz} = \\chi_{xzy}',
      '\\chi_{yxz} = \\chi_{yzx}',
      '\\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx}',
      '\\chi_{zxy} = \\chi_{zyx}',
      '\\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note: "Monoclinic Type-III family check (axial branch, mirror plane normal to z carries the prime).",
  },

  // --- Orthorhombic family: mmm' / m'm'2 --------------------------------------------
  {
    group: "mmm'",
    tensor: 'MD',
    tr: 'c',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx}',
      '\\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx}',
      '\\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note: "Orthorhombic Type-III family check, centrosymmetric member (axial c-type branch).",
  },
  {
    group: "m'm'2",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xyz} = \\chi_{xzy}',
      '\\chi_{yxz} = \\chi_{yzx}',
      '\\chi_{zxy} = \\chi_{zyx}',
    ],
    source: GENERATOR_DERIVATION,
    note: 'Orthorhombic Type-III family check, polar member (c-type ED SHG tensor).',
  },

  // --- Tetragonal family: 4'mm' / 4/m'm'm' -------------------------------------------
  {
    group: "4'mm'",
    tensor: 'ED',
    tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note: "i-type results depend only on the rotation parts, so 4'mm'(ED,i) = 4mm(ED,i), matching the existing 4mm golden fixture exactly.",
  },
  {
    group: "4'mm'",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}',
      '\\chi_{zxx} = -\\chi_{zyy}',
    ],
    source: GENERATOR_DERIVATION,
    note: 'Tetragonal Type-III family check, polar member (c-type ED SHG tensor).',
  },
  {
    group: "4'mm'",
    tensor: 'MD',
    tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note: 'Axial i-type branch for the same group, exercising the det(g) factor for a Type-III group.',
  },
  {
    group: "4/m'm'm'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note: 'Tetragonal Type-III family check, centrosymmetric member (c-type ED SHG tensor).',
  },

  // --- Trigonal family (additional members): 32' / 3m' ------------------------------
  {
    group: "32'",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}',
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note: "Additional trigonal Type-III coverage alongside -3'm'.",
  },
  {
    group: "3m'",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
    ],
    source: GENERATOR_DERIVATION,
    note: 'Trigonal polar Type-III member (c-type ED SHG tensor).',
  },

  // --- Hexagonal family (centrosymmetric member): 6/m'm'm' --------------------------
  {
    group: "6/m'm'm'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note: 'Hexagonal Type-III family check, centrosymmetric member (c-type ED SHG tensor).',
  },

  // --- Cubic family: m'-3' / 4'32' ------------------------------------------------------
  {
    group: "m'-3'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: GENERATOR_DERIVATION,
    note: 'Cubic Type-III family check (c-type ED SHG tensor) -- the single fully-antisymmetric-index cubic invariant.',
  },
  {
    group: "m'-3'",
    tensor: 'MD',
    tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: GENERATOR_DERIVATION,
    note: "i-type results depend only on the rotation parts, so m'-3'(MD,i) = m-3(MD,i), the cubic axial-tensor analogue of the relation above.",
  },
  {
    group: "4'32'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: GENERATOR_DERIVATION,
    note: "Additional cubic Type-III coverage -- a different generator combination (chiral 432-based) reduces to the same invariant as m'-3'(ED,c).",
  },

  // --- MD (axial, i-type) coverage for Type-I groups ---------------------------------
  {
    group: '4/mmm',
    tensor: 'MD',
    tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note: 'Exercises the det(g) axial branch of transformTensor() for a Type-I tetragonal group.',
  },
  {
    group: '622',
    tensor: 'MD',
    tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note: 'Exercises the det(g) axial branch of transformTensor() for a Type-I hexagonal group.',
  },
  {
    group: 'm-3m',
    tensor: 'MD',
    tr: 'i',
    expected: ['All components are zero.'],
    source: GENERATOR_DERIVATION,
    note: "Cubic m-3m has no non-zero axial rank-3 invariant (its mirrors forbid the m'-3'-style fully-antisymmetric form), unlike the lower-symmetry groups above -- a useful negative case for the det(g) branch.",
  },

  // --- EQ (rank-4) coverage ------------------------------------------------------------
  {
    group: 'm-3m',
    tensor: 'EQ',
    tr: 'i',
    expected: [
      '\\chi_{xxxx} = \\chi_{yyyy} = \\chi_{zzzz}',
      '\\chi_{xxyy} = \\chi_{xxzz} = \\chi_{yyxx} = \\chi_{yyzz} = \\chi_{zzxx} = \\chi_{zzyy}',
      '\\chi_{xyxy} = \\chi_{xyyx} = \\chi_{xzxz} = \\chi_{xzzx} = \\chi_{yxxy} = \\chi_{yxyx} = \\chi_{yzyz} = \\chi_{yzzy} = \\chi_{zxxz} = \\chi_{zxzx} = \\chi_{zyyz} = \\chi_{zyzy}',
    ],
    source: GENERATOR_DERIVATION,
    note: 'Rank-4 EQ fixture for the highest-symmetry cubic group: three independent invariants (the cubic analogue of the elastic constants C11/C12/C44 pattern, here without Voigt symmetry between the two middle indices).',
  },

  // =============================================================================
  // Birss Table 4e verification: all 21 symbol classes at rank 3 (ED i-type)
  // One representative group per symbol class (A_n through U_n).
  // =============================================================================

  {
    group: '1', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxx}', '\\chi_{xxy} = \\chi_{xyx}', '\\chi_{xxz} = \\chi_{xzx}',
      '\\chi_{xyy}', '\\chi_{xyz} = \\chi_{xzy}', '\\chi_{xzz}',
      '\\chi_{yxx}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{yxz} = \\chi_{yzx}',
      '\\chi_{yyy}', '\\chi_{yyz} = \\chi_{yzy}', '\\chi_{yzz}',
      '\\chi_{zxx}', '\\chi_{zxy} = \\chi_{zyx}', '\\chi_{zxz} = \\chi_{zzx}',
      '\\chi_{zyy}', '\\chi_{zyz} = \\chi_{zzy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row A3 (18 independent components).',
  },
  {
    group: '2', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx}', '\\chi_{xyz} = \\chi_{xzy}',
      '\\chi_{yxz} = \\chi_{yzx}', '\\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx}', '\\chi_{zxy} = \\chi_{zyx}', '\\chi_{zyy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row B3 (8 independent components).',
  },
  {
    group: 'm', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxx}', '\\chi_{xxy} = \\chi_{xyx}', '\\chi_{xyy}', '\\chi_{xzz}',
      '\\chi_{yxx}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{yyy}', '\\chi_{yzz}',
      '\\chi_{zxz} = \\chi_{zzx}', '\\chi_{zyz} = \\chi_{zzy}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row C3 (10 independent components).',
  },
  {
    group: '222', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy}', '\\chi_{yxz} = \\chi_{yzx}', '\\chi_{zxy} = \\chi_{zyx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row D3 (3 independent components).',
  },
  {
    group: 'mm2', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xxz} = \\chi_{xzx}', '\\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx}', '\\chi_{zyy}', '\\chi_{zzz}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row E3 (5 independent components).',
  },
  {
    group: '4', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
      '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row F3 (4 independent components).',
  },
  {
    group: '-4', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}',
      '\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx}',
      '\\chi_{zxx} = -\\chi_{zyy}', '\\chi_{zxy} = \\chi_{zyx}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row G3 (4 independent components).',
  },
  {
    group: '422', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row H3 (1 independent component).',
  },
  {
    group: '4mm', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row I3 (3 independent components).',
  },
  {
    group: '-42m', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx}', '\\chi_{zxy} = \\chi_{zyx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row J3 (2 independent components).',
  },
  {
    group: '3', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}',
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
      '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row K3 (6 independent components).',
  },
  {
    group: '32', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row L3 (2 independent components).',
  },
  {
    group: '3m', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}',
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row M3 (4 independent components).',
  },
  {
    group: '6', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
      '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row N3 (4 independent components).',
  },
  {
    group: '-6', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}',
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row O3 (2 independent components).',
  },
  {
    group: '622', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row P3 (1 independent component).',
  },
  {
    group: '6mm', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row Q3 (3 independent components).',
  },
  {
    group: '-6m2', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row R3 (1 independent component).',
  },
  {
    group: '23', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row S3 (1 independent component).',
  },
  {
    group: '432', tensor: 'ED', tr: 'i',
    expected: ['All components are zero.'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row T3 (all zero — piezoelectricity forbidden in 432).',
  },
  {
    group: '-43m', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row U3 (1 independent component).',
  },
];
